CREATE TABLE order_items(
 	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	`order_id` INT(11) UNSIGNED NOT NULL,
 	FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 	`product_id` INT(11) UNSIGNED NOT NULL,
 	FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 	`quantity` INT(6) UNSIGNED NOT NULL,
 	`unit_price` INT(11) UNSIGNED NOT NULL,
 	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
 	`update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
 );
