CREATE TABLE products(
 	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 	`category_id` INT(11) UNSIGNED NOT NULL,
 	FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 	`name` VARCHAR(50) NOT NULL,
 	`description` VARCHAR(255) NOT NULL,
 	`price` INT(11) NOT NULL,
 	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
 );

