-- task 3:

-- Write a SQL query to retrieve the total revenue generated by each product category. 
-- Display the category name along with the total revenue in descending order of the revenue.

SELECT c.name AS category_name,SUM(oi.quantity*oi.unit_price) AS revenue
FROM categories c
INNER JOIN products p ON p.category_id = c.id
INNER JOIN order_items oi ON oi.product_id = p.id
GROUP BY p.category_id ORDER BY revenue DESC;

